#!/usr/bin/env php
<?php
// 启动文件目录
defined('ROOT') or define('ROOT', __DIR__);
//日志目录
defined('LOG') or define('LOG', ROOT . DIRECTORY_SEPARATOR . 'log');

// include composer的自动加载类完成命名空间的注册
$loader = include_once ROOT . '/vendor/autoload.php';
$loader->add('Thumb\\', ROOT . '/src');//这里是因为src目录是自定义的目录,不是vendor下面的目录.所以要这样加载

function initCheck()
{
    if (version_compare(phpversion(), '7.0.0', '<')) {
        die("php version must >= 7.0.0");
    }
    if (version_compare(swoole_version(), '1.9.15', '<')) {
        die("swoole version must >= 1.9.15");
    }
}


function commandParser()
{
    global $argv;
    $command = $argv[1] ?? null;
    $server = $argv[2] ?? null;
    return ['command' => $command, 'server' => $server];
}

function startServer($server)
{
    global $argv;
    switch (strtolower($server)) {
        case 'http':
            {
                include ROOT.DIRECTORY_SEPARATOR.'http/HttpServer.php';
                $http = new HttpServer();
                $http->start();
                break;
            }

        default:
            {
                help($command = 'help');
            }
    }
    return;
}

function stopServer($server)
{
    global $argv;
    switch (strtolower($server)) {
        case 'http':
            {
                $path = ROOT . '/protocol/http';
                $pid_file = $path . '/server.pid';
                break;
            }
        default:
            {
                help($command = 'help');
            }
    }

    if (!is_file($pid_file)) {
        echo "error: pid file {$pid_file} is not exist! \n";
        return;
    }
    $pid = intval(file_get_contents($pid_file));
    if (!swoole_process::kill($pid, 0)) {
        echo "error: pid={$pid} not exist \n";
        return;
    }
    // 发送信号，终止进程
    swoole_process::kill($pid, SIGTERM);
    // 回收master创建的子进程（manager,worker,taskworker）
    swoole_process::wait();
    //等待2秒
    $nowtime = time();
    while (true) {
        usleep(1000);
        if (!swoole_process::kill($pid, 0)) {
            echo "------------stop info------------\n";
            echo "successful: server stop at " . date("Y-m-d H:i:s") . "\n";
            echo "\n";
            @unlink($pid_file);
            break;
        } else {
            if (time() - $nowtime > 2) {
                echo "-----------stop info------------\n";
                echo "error: stop server failed. please try again \n";
                echo "\n";
                break;
            }
        }
    }
}

function help($command)
{
    switch (strtolower($command . '-' . 'help')) {
        case 'start-help':
            {
                echo "------------swoolefy启动服务命令------------\n";
                echo "1、执行php swoolefy start http 即可启动http server服务\n\n";
                echo "2、执行php swoolefy start websocket 即可启动websocket server服务\n\n";
                echo "3、执行php swoolefy start rpc 即可启动rpc server服务\n\n";
                echo "4、执行php swoolefy start udp 即可启动udp server服务\n\n";
                echo "5、执行php swoolefy start monitor configfile，例如php swoolefy start monitor config9502.php 即在当前终端启动monitor 监控文件自动重启worker服务\n\n";
                echo "6、执行php swoolefy start monitor configfile，例如php swoolefy start monitor config9502.php -d 即以守护进程启动monitor 监控文件自动重启worker服务\n\n";
                echo "\n";
                break;
            }
        case 'stop-help':
            {
                echo "------------swoolefy终止服务命令------------\n";
                echo "1、执行php swoolefy stop http 即可终止http server服务\n\n";
                echo "2、执行php swoolefy stop websocket 即可终止websocket server服务\n\n";
                echo "3、执行php swoolefy stop rpc 即可终止rpc server服务\n\n";
                echo "4、执行php swoolefy stop udp 即可终止rpc server服务\n\n";
                echo "5、执行php swoolefy stop monitor port，例如php swoolefy stop monitor 9502 即可终止monitor 监控文件自动重启worker服务\n\n";
                echo "\n";
                break;
            }
        default:
            {
                echo "------------欢迎使用swoolefy------------\n";
                echo "有关某个命令的详细信息，请键入 help 命令:\n\n";
                echo "1、php swoolefy start help 查看详细信息!\n\n";
                echo "2、php swoolefy stop help 查看详细信息!\n\n";
            }
    }
}

function commandHandler()
{
    $command = commandParser();
    if (isset($command['server']) && $command['server'] != 'help') {
        switch ($command['command']) {
            case "start":
                {
                    startServer($command['server']);
                    break;
                }
            case 'stop':
                {
                    stopServer($command['server']);
                    break;
                }
            case 'help':
            default:
                {
                    help($command['command']);
                }
        }
    } else {
        help($command['command']);
    }
}

initCheck();
commandHandler();

